################# Makefile for MaskScorer.py ##########################

#### Creation Date: June 9, 2016 
MAKE=make

check:
	(cd ../../lib; python2 -m unittest masks)
	(rm ../../lib/testImg*.png)
	(./maskcompcheckfiles.sh)
