################### Makefile for All Tools ##########################

#### Creation Date: February 28, 2017
MAKE=make

check:
	(python2 -m unittest validatorUnitTest)

render_readmes_to_html:
	(jupyter-nbconvert --to html ValidatorReadMe.ipynb)
