################# Makefile for DetectionScorer.r ##########################

#### Creation Date: June 9, 2016 
MAKE=make

check:
	(python2 -m unittest DetectionScorer)
	(./detcompcheckfiles.sh)

makecompcheckfiles:
	(./detcompcheckfiles.sh)
