################# Makefile for DetectionScorer.r ##########################

#### Creation Date: June 9, 2016 
MAKE=make

check:
	(Rscript DetectionScorerUnitTest.r)
	(./detcompcheckfiles.sh)

makecompcheckfiles:
	(./detcompcheckfiles.sh)
