################# Makefile for MaskScorer.py ##########################

#### Creation Date: June 9, 2016 
MAKE=make

check:
	(./run_integration_tests.sh)

render_readmes_to_html:
	(jupyter-nbconvert --to html LocalizationVisualizerReadMe.ipynb)
